from enum import Enum
class States(Enum):
    WAITING_DONATION = "WAITING_DONATION"
    IDENTIFYING = "IDENTIFYING"
    ID_SUCCESS = "SUCCESS"
    ID_FAILURE = "FAILURE"
    WAITING_DELIVERY = "WAITING_DELIVERY"
    DELIVERY_SUCCESS = "DELIVERY_SUCCESS"
    DELIVERY_FAILURE = "DELIVERY_FAILURE"
